### ISSUE TITLE
./configure --enable-qt4 fails

### ISSUE THREAD

**Issue by giuliomoro** [rncbc/qmidinet#1]
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether gcc needs -traditional... no
checking for qmake-qt4... /usr/bin/qmake-qt4
checking for qmake... /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
checking for Qt library version >= 4.4... yes
checking for moc... /usr/lib/x86_64-linux-gnu/qt4/bin/moc
checking for uic... /usr/lib/x86_64-linux-gnu/qt4/bin/uic
checking for lupdate... /usr/lib/x86_64-linux-gnu/qt4/bin/lupdate
checking for lrelease... /usr/lib/x86_64-linux-gnu/qt4/bin/lrelease
checking for main in -lm... yes
checking for main in -lX11... yes
checking for main in -lXext... yes
checking for main in -lasound... yes
checking for main in -ljack... no
configure: WARNING: **\* JACK library not found.
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking for sys/stat.h... (cached) yes
checking for unistd.h... (cached) yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking alsa/asoundlib.h usability... yes
checking alsa/asoundlib.h presence... yes
checking for alsa/asoundlib.h... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating qmidinet.spec
config.status: creating src/src.pri
config.status: creating src/qmidinet.desktop
config.status: error: cannot find input file: `src/config.h.in'

**Comment by giuliomoro** [comment]
workaround: 

```
$ touch src/config.h.in
$ ./configure --enable-qt4 
$ printf "#define PACKAGE_NAME \"qmidinet\"\n#define PACKAGE_VERSION \"1.2.3\"\n" > src/config.h
$ make
```

**Comment by rncbc** [comment]
just a guess:

you probably failed to ./configure (--enable-qt5) before, probably due 
to lack of qt5 development files there and trying to restart with 
./configure --enable-qt4 and having all that trouble...

next time start clean from scratch, by doing so first:

   ./autogen.sh clean
   ./autogen.sh
   ./configure --enable-qt4
   make

hth.

## cheers

rncbc aka. Rui Nuno Capela
