### ISSUE TITLE
Headless (no-gui) mode

### ISSUE THREAD

**Issue by jofemodo** [rncbc/qmidinet#4]
It would be very useful for many use-cases having a headless mode, a "no-gui" flag.
Using "multimidicast" could be an option, but it lacks of jack-midi support. Also, it's not maintained anymore.

Thanks!

**Comment by rncbc** [comment]
but it has o.O

`qmidinet --help` or `man qmidinet` should have told you that :)

**Comment by wyleu** [comment]
My bad.

Heavy to compile. we presumably don't want to import all the qt components if we only ever want to run it headless.

**Comment by wyleu** [comment]
Built it on zynthian with qt5 components.
ran it headless -g

It runs but I'm not sure it's doing anything . . .
I can't see anything in aconnect -lo or qjackctl 

or even get a response from qmidinet --help

**Comment by wyleu** [comment]
Install on a raspberrypi3 zynthian
Installed Qt5 components ( sudo apt-get install qt5-default)

Builds ok, can’t seem to run it. starts
on -gj (headless, jack)
but don’t see anything in aconnect -lo
or indeed qmidinet --help

Not sure it’s doing anything . . .

**Comment by rncbc** [comment]
./configure report (and config.log)  might be of help here.

anyway, the output of `qmidinet --help` should be the following:
```
QmidiNet - A MIDI Network Gateway via UDP/IP Multicast

Usage: qmidinet [options]

Options:

  -n, --num-ports=[num-ports]
        Use this number of ports (default = 1)

  -i, --interface=[interface]
        Use specific network interface (default = all)

  -u, --address, --udp-addr=[address]
        Use specific network address (default = 225.0.0.37)

  -p, --port, --udp-port=[port]
        Use specific network port (default = 21928)

  -a, --alsa-midi[=flag]
        Enable ALSA MIDI (0|1|yes|no|on|off, default = 1)

  -j, --jack-midi[=flag]
        Enable JACK MIDI (0|1|yes|no|on|off, default = 1)

  -g, --no-gui
        Disable the graphical user interface (GUI)

  -h, --help
        Show help about command line options

  -v, --version

```
if that's not showing to you then you have a broken build system, i suspect.
cheers

ps. im afraid `qmidinet -gj` doesn't do nothing anyway sorry: it's better spelled as `qmidinet -g -j` ;)

**Comment by jofemodo** [comment]
Sorry ... i didn't note the option 0;-)
