### ISSUE TITLE
Unicast

### ISSUE THREAD

**Issue by virtualdxs** [rncbc/qmidinet#9]
Would it be possible to add support for udp over unicast IP? I wanted to experiment with this over a Wireguard VPN connection (I know there'll be high latency but I still want to mess with it) but Wireguard does not support multicast and I'd rather avoid VXLAN if possible. I might attempt to write such a patch myself, but before I go through that effort (especially since I haven't touched C++ in a long time) I'd like to verify that there isn't a technical reason it's not doable.

**Comment by rncbc** [comment]
that would pervert the whole purpose and idea of this _plug-and-play_ utility,and also, qmidinet range is (should be) restricted to your local LAN segment--it is not advisable, even if it ever works at all, to get multicast traffic through a router or any other internet gateway--whatever you're trying to do, please don't :)

even if it could go through (including a unicast scenario as you ask) it would suffer with terrible latency and way worst, jitter and loss, having random behavior and experience on each time you try... it could be fun but as a musician what would be the point?

by the end of the day, you may resort to some other utility and protocol, possibly one supporting rtpMIDI, for example.
byee

**Comment by virtualdxs** [comment]
> that would pervert the whole purpose and idea of this plug-and-play utility
Maybe it goes beyond the original idea, but adding a flag to allow unicast doesn't need to get in the way of the plug and play nature of the default behavior.

> even if it could go through (including a unicast scenario as you ask) it would suffer with terrible latency and way worst, jitter and loss
For one of the things I wanted to try with this, the latency I'm looking at for is ~4ms, with about 1.5ms of jitter and no loss.

> by the end of the day, you may resort to some other utility and protocol, possibly one supporting rtpMIDI, for example.
That's probably what I'll end up doing. Thanks for pointing me in the direction of rtpMIDI!
